name: Hive_Of_Thoughts_RPG
main: com.hiveofthoughts.mc.rpg.Main
version: 1.0.0
description: Hive Of Thoughts RPG Plugin
author: Michael George (PolitePingu)
website: http://themepark.theonestone.com
commands:
  rpg:
    description: Can be used to interact with the RPG functions of the server.
    permission: hotmc.rpg
    usage: /<command>
permissions:
  hotmc.rpg:
    description: Allows use of the /rpg command on rpg servers
    default: true
