name: Hive_Of_Thoughts_ARCADE
main: com.hiveofthoughts.mc.arcade.ArcadeServer
version: 1.0.0
description: Hive Of Thoughts Arcade Plugin
author: Michael George (PolitePingu)
website: http://mc.kaspyre.com
commands:
  rpg:
    description: Can be used to interact with the RPG functions of the server.
    permission: hotmc.rpg
    usage: /<command>
permissions:
